version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - awesome_theme_db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:php7.1-apache
     volumes:
       - .:/var/www/html/wp-content/themes/awesome-theme/
     ports:
       - "8888:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: wordpress
volumes:
    awesome_theme_db_data:
